### ISSUE TITLE
Reason for lambda.z excluded

### ISSUE THREAD

**Issue by kirstenbergmann** [billdenney/pknca#102]
Hi Bill

lambda.z (and all related parameters) are not presented in the results if less than "min.hl.points" number of points are available for the linear regression. Two questions related to this:
- are there other criteria that will automatic exclude lambda.z?
- would it be possible to add a note in the exclude column of the output specifying something like "Minimum number of points < (min.hl.points)"

Thanks
Kirsten

**Comment by billdenney** [comment]
Insufficient number of points is the only reason that PKNCA will currently not provide a calculated half-life result.

To exclude other results or for other reasons, please see the `exclude()` function.  When you use the exclude function, it will apply to any parameter excluded specifically and to any parameter that depends on that parameter or that is calculated at the same time as that parameter.  For example, excluding half-life will also exclude lambda.z, aucinf (whether aucinf.pred or aucinf.obs), and clearance related to aucinf.  (Note that this is not exhaustive; all dependent parameters are automatically excluded, and PKNCA knows which parameters are dependent on others.)

That is a good idea to add the note to the exclude column when not calculated due to insufficient number of points.  I will leave this issue open until that is implemented.

**Comment by billdenney** [comment]
I just committed a fix to this in GitHub.

**Comment by kirstenbergmann** [comment]
Hi Bill

Thanks for including this. I just tried it out and found that the value set in min.hl.r.squared is not used in the text in exclude. I set min.hl.r.squared=0.85 but the exclude text is Half-life r-squared < 0.9. The same is the case with span.ratio (I didnt try changing AUC percentrage extrapolated but it may be the same issue). 

Best regards
Kirsten
