### ISSUE TITLE
Calculation of AUCinf and half-life

### ISSUE THREAD

**Issue by abuhelwa** [billdenney/pknca#107]
While I understand why `pk.nca` is unable to calculate `aucinf` and half-life for Subject 1 but I am not quite sure why `pk.nca` is not able to calculate `aucinf` for sbjects 2 and 3 as an example? I can see a decent terminal phase for both and yet returns this warning: ` Too few points for half-life calculation (min.hl.points=3 with only 2 points)`

Could you please shed some light on how `aucinf` and half-life are exactly calculated and how to get it to calculate AUCinf for such PK profiles? 

Subject 1:
![conc3](https://user-images.githubusercontent.com/18608006/62999352-53705080-bead-11e9-8f89-5b16838afee2.png)

Subject2:

![conc](https://user-images.githubusercontent.com/18608006/62998761-a943f900-beab-11e9-84b8-7c0169b1685d.png)

Subject 3:

![conc2](https://user-images.githubusercontent.com/18608006/62998864-ed36fe00-beab-11e9-97e6-0a6f84fd1fef.png)

**Comment by billdenney** [comment]
By default, PKNCA starts evaluating half-life after T<sub>max</sub>.  The rationale for this is because at T<sub>max</sub>, the compound is likely still being absorbed-- it's just that distribution or elimination switch to being faster than absorption at some point between the measurement before T<sub>max</sub> and the point after.

If you want to allow an attempt at calculation for the second and third examples, you can set PKNCA to allow the point at T<sub>max</sub> with: `PKNCA.options(allow.tmax.in.half.life=TRUE)`.
