### ISSUE TITLE
pk.nca(data obj) run time very long

### ISSUE THREAD

**Issue by Ravua1992** [billdenney/pknca#117]
Hello Bill, 

My name is Abhi and I am trying to learn to use PKNCA. I am simulating 9000 pk profiles using mrgsolve. 
I am currently trying to run NCA on a subset of the data (1000 patients) to verify things are running smoothly and the run time appears to be very long even for 1000 patients for single dose administration grouping only by subject. 
My run started over an hour ago and it appears to be still performing NCA. 

Is there an estimate for the average run time to perform NCA analysis for 1000 patients ? Is there a shorter way to read output from mrgsolve and create a PKNCAdata object ? I am currently saving the mrgsolve output as a data frame to create conc+time,  dose+time objects separately and combine them create PKNCAdata object. 
 
The code I am using is below and is exactly as the Theophylline example.  
```r
# Load your concentration-time data
myrawconcdata <- read.csv("myconc.csv", stringsAsFactors=FALSE)
# Load your dose data
myrawdosedata <- read.csv("mydose.csv", stringsAsFactors=FALSE)
# Put your concentration data into a PKNCAconc object
myconc <- PKNCAconc(data=myrawconcdata,
                    formula=conc~time|treatment+subject/analyte)
# Put your dose data into a PKNCAdose object
mydose <- PKNCAdose(data=myrawdosedata,
                    formula=dose~time|treatment+subject)
# Combine the two (and automatically determine the intervals of
# interest
mydata <- PKNCAdata(myconc, mydose)
# Compute the NCA parameters
myresults <- pk.nca(mydata)
# Summarize the results
summary(myresults)
```

Thank you, 
Abhi

**Comment by billdenney** [comment]
The current version of PKNCA should not take an hour to run with 1000 simulated, typical profiles.  Did you simulate a dense grid of time points (for example, a typical PK profile for NCA would have about 5 to 15 samples after Tmax)?  Half-life calculations can take a long time if there is a dense grid of points because it has to test all feasible point counts from Tlast.

A recent effort with approximately 3 to 12 samples after Tmax took about 2 minutes with 2600 subjects, so I’m guessing that the time is related to many samples and half-life calculation.

The GitHub version of PKNCA speeds up half-life calculations by about 50%.

**Comment by billdenney** [comment]
One other item that I’m working on is that the data provenance hash takes a relatively long time to generate for larger data sets, but there isn’t a way to speed that right now (though, I am working on it).

**Comment by Ravua1992** [comment]
Hello Bill, Thank you for the response. I have many points for the terminal phase and as you pointed out this might be the reason why the run time is long. I tested the PKNCA package with other data set (not as many observations) and the results are as expected and run time was short as well. Closing this issue now. 
-Abhi

**Comment by billdenney** [comment]
I'm glad that the answer helped.  I am constantly looking for ways to improve PKNCA, and I'll keep this in mind for ways to improve the performance.
