### ISSUE TITLE
tmax/tlast always computed

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#118]
If I do the following, tmax and tlast are computed twice. I was hoping that they would only be computed once,  or at least if they were computed twice they wouldn't be relative to the starting time for each interval.

``` r
library(magrittr)

pk_data_test <- tibble::tibble(Animal = "1",
                               Dose = 0.5,
                               Time = c(0, 0.0833, 0.25, 0.5, 1, 2, 4, 8, 24),
                               Conc = c(0, 200, 100, 50, 40, 20, 10, 8, 6))

## Create a simple data.frame containing dose times
dose.times <- tibble::tibble(Time=0)

## Merge animals and dose.times to create a data frame containing the
## dose times and amounts for each animal
d.dose <- tidyr::crossing(pk_data_test %>% dplyr::select(Animal, Dose) %>% unique(), dose.times)

## Create a PKNCAconc object for our pk data
conc <- PKNCA::PKNCAconc(pk_data_test, Conc~Time|Animal)

## Create a PKNCAdose object for our dosing schedule
dose <- PKNCA::PKNCAdose(d.dose, Dose~Time|Animal)


## Create a PKNCAdata object from the conc and dose objects and specify
## the desired intervals for which to compute PK parameters
pk_nca_data <- PKNCA::PKNCAdata(conc,
                                dose,
                                intervals=data.frame(start = c(0, 0.0833),
                                                     end = c(24, 24),
                                                     tmax = c(TRUE, FALSE),
                                                     cmax = c(TRUE, FALSE),
                                                     cmin = c(FALSE, TRUE),
                                                     half.life = c(TRUE, TRUE)))

## Call pk.nca to compute the parameters
pk_nca_results <- PKNCA::pk.nca(pk_nca_data)

pk_nca_results$result
```

**Comment by billdenney** [comment]
There's not a straight-forward way around this.

PKNCA has the philosophy that any parameter required for calculation should be in the results table.  `tmax` and `tlast` are both required for half-life calculation:  `tmax` is needed to exclude it from the points used to assess `lambda.z`, and `tlast` is needed to assess the times when `half.life` can be calculated (what is the last point).

And, all calculations within an interval are relative to that interval starting time.  The rationale for this is illustrated by `tmax` where `tmax` after multiple dosing should be relative to that last dose.  While I understand that having `tmax` relative to a dose may also be rational, there are instances such as divided dosing where it will not be rational.  And, since dosing information is optional for NCA calculations, it can't be relative to the dose since dose may not be present.

You can convert `tmax` and `tlast` to be on an absolute time scale by adding `start` to them.
