### ISSUE TITLE
PKNCA.options.describe and PKNCA.options("single.dose.auc") not working

### ISSUE THREAD

**Issue by toothpicky** [billdenney/pknca#123]
The PKNCA package documentation mentioned a function not available in the package: PKNCA.options.describe()

Also, documentation advises if only one dose is administered, use the PKNCA.options("single.dose.auc"). However, I get an error message: PKNCA.options does not have value(s) for single.dose.auc.

**Comment by billdenney** [comment]
Thanks for your interest in PKNCA!

I accidentally didn't export the `PKNCA.options.describe()` function.  It will be exported in the next version.  You can use it until then by accessing the private method: `PKNCA:::PKNCA.options.describe("single.dose.aucs")`

As for "single.dose.aucs", it appears that you're missing the "s" at the end.  I see a place in the documentation where I missed the "s", too, and that will be fixed in the next version as well.
