### ISSUE TITLE
AUC calculation

### ISSUE THREAD

**Issue by FangfeiL** [billdenney/pknca#134]
Hi Bill

I have been using the following functions for AUClast and AUCinf calculations, e.g.
my_conc <- c(700, 300, 100, 20, 5, 2)
my_time <- c(0, 1.5, 5, 10, 20, 24)
pk.calc.auc(my_conc, my_time, interval=c(0, 20))
pk.calc.auc(my_conc, my_time, interval=c(0, Inf))

However, the calculated values are higher (or rather, different) when using the basic equations: 
(1) AUC (t1-t2) = [(t2-t1)/2]*(C1+C2)  
(2) AUC0-∞ = AUC(1-last) + (Clast/kel)

I am sure this is not a technical issue but just would like to know why there is a difference. 

Cheers
Fangfei

**Comment by billdenney** [comment]
The default method that PKNCA uses to calculate AUC is the linear-up/log-down method (documented in the `method` argument to `pk.calc.auc()`).  The method you're indicating with the equation for AUC(t1-t2) is the linear trapezoidal method.  Additionally, in your first line, you end the interval at 20 instead of 24 hours.

The code below illustrates that when using the same method and time interval, you get the same answer as the trapezoidal rule:

``` r
library(PKNCA)
library(caTools)
my_conc <- c(700, 300, 100, 20, 5, 2)
my_time <- c(0, 1.5, 5, 10, 20, 24)
pk.calc.auc(my_conc, my_time, interval=c(0, 20))
#> [1] 1702.037
pk.calc.auc(my_conc, my_time, interval=c(0, Inf))
#> [1] 1715.133

trapz(x=my_time, y=my_conc)
#> [1] 1889
pk.calc.auc(my_conc, my_time, interval=c(0, 24), options=list(auc.method="linear"))
#> [1] 1889
```

<sup>Created on 2020-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
