### ISSUE TITLE
how to use function clean.conc.blq

### ISSUE THREAD

**Issue by skyee1** [billdenney/pknca#145]
hello:
  I want to use function clean.conc.blq to handle BLQ of column Concentration，but not change,follow is my code!

```r
data$con1 <- clean.conc.blq(data$Concentration.ng.mL., 
                            data$Time.h.,
                            conc.blq = list(first = 0,middle = 'keep', last = 0),
                            check = F)
```

**Comment by billdenney** [comment]
In normal use, `clean.conc.blq()` is not meant to be called directly.  It is used internally by PKNCA when you call `pk.nca()`.

I'm going to guess what you're doing here, but it is more helpful if you're able to provide a reproducible example (easiest using the `reprex` package).

I would guess that one difference between your use and your goal is that you must call `clean.conc.blq()` with data from one subject at a time.  It appears that you're calling with data from all of your subjects simultaneously.

The next issue is that `clean.conc.blq()` returns a data.frame while you appear to be expecting a vector based on your assignment into what I'm guessing is a data.frame.

Another potential issue with directly assigning the values into a column of a data.frame is that the number of rows coming out of `clean.conc.blq()` may not be the same number of rows as the input (not an issue with your code, but it would be an issue if you set `middle = "drop"`).

Based on your question, you're wanting to assign a new column in your data.frame with blq concentrations at the beginning and end set to zero and concentrations in the middle kept.  FYI, that will output almost the exact same values as your input since PKNCA treats zeros as BLQ; the only difference will be that missing values (`NA`) will be dropped.  If your data has no missing values, then the output will be the same as the input.  If your data has missing values, then the code above will have an error because the output of `clean.conc.blq()` will have fewer rows than the input.  And in general, `clean.conc.blq()` is returning a data.frame, so the assignment into a column of a data.frame is not likely what you're looking for.

If this doesn't answer your question, can you please provide a reproducible example illustrating your question with some data for inputs and what you're hoping to achieve?

**Comment by skyee1** [comment]
Hello:
 Thanks for your reply.Follow is a reproducible example.

```
my_conc <- data.frame(conc=c('BLQ', 2.5, 3, 'BLQ', 'BLQ', 1.2, 1.1, 'BLQ', 'BLQ'),
                      time=c(0:5, 8, 12, 24),
                      subject=1)
myconc2 <- clean.conc.blq(my_conc$conc,my_conc$time,
                          conc.blq = list('first'=0,'middle'=0.01,'last'=0),
                          check = F)
``` 
   I want to set Values up to the first non-BLQ value as zero,and set Values that are BLQ between the first and last non-BLQ values as 0.01,and set Values that are BLQ after the last non-BLQ value as 0 or NA.

   But when I use the function to handle BLQ,it is not use.

   Please tell me a way to solve my question.

Thank you!

**Comment by billdenney** [comment]
FYI, I found a bug in PKNCA while working through your example (thanks!), so you will need to install the latest github version to make the example below work (`remotes::install_github("billdenney/pknca")`).

The issue is that your concentration data is not numeric.  PKNCA tells you this when you leave `check=TRUE`:

``` r
library(PKNCA)
my_conc <- data.frame(conc=c('BLQ', 2.5, 3, 'BLQ', 'BLQ', 1.2, 1.1, 'BLQ', 'BLQ'),
                      time=c(0:5, 8, 12, 24),
                      subject=1)
myconc2 <- clean.conc.blq(my_conc$conc,my_conc$time,
                          conc.blq = list('first'=0,'middle'=0.01,'last'=0),
                          check = F)

myconc2 <- clean.conc.blq(my_conc$conc,my_conc$time,
                          conc.blq = list('first'=0,'middle'=0.01,'last'=0),
                          check = TRUE)
#> Error in check.conc.time(conc, time): Concentration data must be numeric and not a factor
```

<sup>Created on 2021-06-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


When you turned off checking of the inputs (which is only intended to speed up analysis and not intended to be turned off, in general), you removed that check.

When converting to numeric (and installing the version on github), your example works as expected:

``` r
library(PKNCA)
my_conc <-
  data.frame(
    conc_character=c('BLQ', 2.5, 3, 'BLQ', 'BLQ', 1.2, 1.1, 'BLQ', 'BLQ'),
    time=c(0:5, 8, 12, 24),
    subject=1
  )
my_conc$conc <-
  as.numeric(
    ifelse(
      my_conc$conc_character %in% "BLQ",
      0,
      my_conc$conc_character
    )
  )

# my_conc$conc is numeric while my_conc$conc_character is a character vector as
# is visible by the quotes around the values.
my_conc$conc
#> [1] 0.0 2.5 3.0 0.0 0.0 1.2 1.1 0.0 0.0
my_conc$conc_character
#> [1] "BLQ" "2.5" "3"   "BLQ" "BLQ" "1.2" "1.1" "BLQ" "BLQ"
myconc2 <-
  clean.conc.blq(
    my_conc$conc,
    my_conc$time,
    conc.blq = list('first'=0, 'middle'=0.01, 'last'=0)
  )
myconc2
#>   conc time
#> 1 0.00    0
#> 2 2.50    1
#> 3 3.00    2
#> 4 0.01    3
#> 5 0.01    4
#> 6 1.20    5
#> 7 1.10    8
#> 8 0.00   12
#> 9 0.00   24
```

<sup>Created on 2021-06-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by skyee1** [comment]
Hello：
Thanks for your help!
Good luck!
