### ISSUE TITLE
calculate mrt.md.obs

### ISSUE THREAD

**Issue by skyee1** [billdenney/pknca#148]
Hello,
PKNCA is a great package. Thanks to the authors for maintaining this for the community.

I try to calculate the parameters of multi dose data. The data are as follows. The route of administration is extravascular. Dose interval is 12h. Dosage is 20mg.

```r
subject <- '102'
day <- rep(c(1,4,5,6),c(13,2,2,25))
time <- c(0:12,0,12,0,12,seq(0,48,by=2))

conc <- c(0,70,150,140,110,100,250,180,130,80,60,50,20,
          10,9.8,9,8,7,6,4,9,27,76,100,97,83,295,203,136,
          90,70,300,203,120,90,72,55,25,15,10,9,6)
dose = 20
tau = 12

data <- data.frame(subject = subject,
                    time = time,
                    day = day,
                    conc = conc,
                    dose = dose,
                    tau = tau)
conc_obj <- PKNCAconc(data, conc~time|subject + day)

d_dose <- unique(data[data$time==0 | data$time==12 ,])

dose_obj <- PKNCAdose(d_dose, dose~time|subject + day)

intervals_manual <-
  data.frame(start=0, end=c(max(data$time),Inf),
             auclast = c(T,F),
             mrt.md.obs = c(F,T),
             cav = c(F,T),
             swing = c(F,T),
             vss.obs = c(F,T),
             aumclast = c(F,T))

data_obj <- PKNCAdata(conc_obj, dose_obj ,intervals= intervals_manual)
results_obj <- pk.nca(data_obj)
```

when I run this code, I receive thr error.
```r
Error in (function (conc, time, volume, duration.conc, dose, time.dose,  : 
  Error with interval subject=102, day=1, start=0, end=Inf: Cannot find argument 'tau' for NCA function 'pk.calc.mrt.md'
```

But if I use the parameter "mrt.obs", its value is different with the result of the software "winnolin".

This problem has puzzled me for a long time, how to calculate specific parameters related to multi dose data when using multi dose data.

Hope to get your reply as soon as possible！

**Comment by billdenney** [comment]
Thank you for the reproducible example of your issue.

I don't have access to WinNonlin nor its manual.  So, I cannot compare to WinNonlin results, but I think that the result will likely be the same if you use the `mrt.last` parameter instead.

For steady-state administration, you should typically use the `mrt.last` which for multiple dosing would be equivalent to the MRT from time 0 to tau.  The `mrt.md.obs` parameter is used to account for nonlinearity in PK between the first and last dose, and it requires a full, single-dose AUC0-inf obtained separately from the multiple-dose interval.  (Your data appears to be a standard multiple-dose study without a separate single-dose AUC0-inf.

Unfortunately, the `mrt.md.obs` parameter is not well-integrated into PKNCA; I have never seen it used in practice, and study designs are not often setup to assess `mrt.md.obs`.  (See also the brief discussion in issue #144.)

Based on the information you provided, the study design does not support calculating the `mrt.md.obs` parameter.  It's not precisely clear what your study design is, but based on the data, it appears that dosing was 20 mg every 12 hours from Day 1 to Day 7 (with only a single dose on Day 7), and dense PK profiles were collected on days 1, 6, and 7.  With that, I would recommend setting up your data a bit differently so that you have the time since first dose added to the datasset.  I have added the `time_since_first_dose` column to your data to support this.

And, assuming that your dosing is as I described in the previous paragraph, you would not typically calculate the parameters to infinity other than half-life because the parameters should only be calculated for single-dose data or steady-state data to tau (not to infinity).

Please let me know if the code below fixes your issue:

``` r
library(PKNCA)

subject <- '102'
day <- rep(c(1,4,5,6),c(13,2,2,25))
time <- c(0:12,0,12,0,12,seq(0,48,by=2))

conc <- c(0,70,150,140,110,100,250,180,130,80,60,50,20,
          10,9.8,9,8,7,6,4,9,27,76,100,97,83,295,203,136,
          90,70,300,203,120,90,72,55,25,15,10,9,6)
dose = 20
tau = 12

data <- data.frame(subject = subject,
                   time = time,
                   day = day,
                   conc = conc,
                   dose = dose,
                   tau = tau)
# Added to clarify unique times
data$time_since_first_dose <- (data$day - 1)*24 + data$time

#conc_obj <- PKNCAconc(data, conc~time_since_first_dose|day + subject)
# Removed grouping by day because it is handled by the interval start and end
# now; also when grouping data, the subject should (almost) always be provided
# as the last grouping level
conc_obj <- PKNCAconc(data, conc~time_since_first_dose|subject)

# The original dose information appears to be inaccurate based on the
# concentration-time profiles since there appears to also have been a dose on
# Day 6 at 24 hours, added here.
d_dose <- unique(data[data$time %in% c(0, 12, 24), ])

# Removed grouping by day because it is handled by the interval start and end
# now; also when grouping data, the subject should (almost) always be provided
# as the last grouping level
#dose_obj <- PKNCAdose(d_dose, dose~time_since_first_dose|day + subject)
dose_obj <- PKNCAdose(d_dose, dose~time_since_first_dose|subject)

intervals_manual <-
  data.frame(start=c(0, 5*24+c(0, 12, 24), 6*24),
             #end=c(max(data$time),Inf),
             end=c(12, 5*24+c(0, 12, 24)+12, Inf),
             auclast = c(rep(TRUE, 4), FALSE),
             #mrt.md.obs = c(F,T),
             mrt.last = c(rep(TRUE, 4), FALSE),
             cav = c(rep(TRUE, 4), FALSE),
             swing = c(FALSE, rep(TRUE, 3), FALSE),
             # vss.obs = c(F,T),
             vss.last = c(FALSE, rep(TRUE, 3), FALSE),
             # aumclast will be automatically calculated when needed
             #aumclast = c(F,T)
             half.life=c(rep(FALSE, 4), TRUE)
  )

data_obj <- PKNCAdata(conc_obj, dose_obj ,intervals= intervals_manual)
results_obj <- pk.nca(data_obj)
summary(results_obj)
#>  start end N   auclast  mrt.last    vss.last       cav     swing half.life
#>      0  12 1 1320 [NC] 5.67 [NC]           .  110 [NC]         .         .
#>    120 132 1  351 [NC] 9.46 [NC]  0.539 [NC] 29.2 [NC] 2400 [NC]         .
#>    132 144 1 1800 [NC] 6.47 [NC] 0.0717 [NC]  150 [NC]  255 [NC]         .
#>    144 156 1 1710 [NC] 5.70 [NC] 0.0667 [NC]  143 [NC]  329 [NC]         .
#>    144 Inf 1         .         .           .         .         . 3.45 [NC]
#> 
#> Caption: auclast, mrt.last, vss.last, cav: geometric mean and geometric coefficient of variation; swing, half.life: arithmetic mean and standard deviation
```

<sup>Created on 2021-06-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by billdenney** [comment]
If you still have a question, please reopen this issue or open a new issue.
