### ISSUE TITLE
IV infusion

### ISSUE THREAD

**Issue by ksl31** [billdenney/pknca#19]
It would be nice if there is option to input infusion length and MRT is calculated accordingly.

**Comment by billdenney** [comment]
I'm looking to improve the dosing specifications so that route of administration and, for IV, infusion parameters are included.  The dosing parameters I will include in a future version of PKNCAdose are:

* Dose amount
* Dose units
* Route (PO, IV, SC, ...)
* Start time (or time if immediate like PO or IV bolus)
* End time (optional, cross-checked against rate if both are given)
* Rate (optional, cross-checked against end time if both are given)

For simplicity, I think that these will have to be given outside the formula that is currently used.  If you can think of a better way to give the information, please let me know.

**Comment by ksl31** [comment]
Just to clarify, so currently IV infusion data and IV bolus data will give same AUC? since it doesn't seem to have a C0 in the final parameters output?

**Comment by billdenney** [comment]
That's correct-- no pre-treatment or cleaning of the data happens in the current version.  For full clarity:  Even if C0 is output, it is not included in the AUC.  To include C0 in the version 0.7, you would have to pre-calculate it, add it to your concentration data (removing the predose concentration if it exists).

Pre-treating data like this will be included in a future version.

**Comment by billdenney** [comment]
I missed responding to this issue a while ago when I added the feature.  There is now a `duration.dose` argument for `PKNCAdose`, and mrt.iv parameters use it (`mrt.iv.last`, `mrt.iv.obs`, and `mrt.iv.pred`).
