### ISSUE TITLE
Pre-treatment of data

### ISSUE THREAD

**Issue by ksl31** [billdenney/pknca#21]
It would be nice if data are checked and corrected before nca run. For example, insertion of initial time points if there is none for non-steady state extravascular and infusion data and set C0=Cmin for steady-state data.

**Comment by billdenney** [comment]
Data cleaning is a planned feature for a future version.  Making sure that we always get it right in the myriad of edge cases is difficult.  Can you provide a list of all data cleaning you would expect so that we can merge it with our list?

**Comment by ksl31** [comment]
Here is my list. 
1) Extravascular and Infusion data: For single dose data, a concentration of zero; for steady-state, the minimum concentration observed during the dose interval. 
2) IV Bolus data: calculates C0 using log-linear regression of first two data points to back-extrapolated C0. If the regression yields a slope >= 0, or at least one of the first two y-values is 0, or if one or both of the points is viewed as an outlier and excluded from the λz regression, then the first observed positive y-value is used as an estimate for C0. 
3) Missing values: if either the time or concentration values are missing, the associated record is excluded from the analysis.  
4) Data points preceding the dose time: If an observation time is earlier than the dose time, that observation is excluded from the analysis. 

Is it also possible to have a table showing the final data used in the calculations after data manipulations? so that it's easier to check what has been excluded.

Thank you!

**Comment by Sibojang9** [comment]
This thread seems quite static for five years. Not sure about any update.

**Comment by billdenney** [comment]
@Sibojang9 , There is no update.  I leave issues open until they reach a resolution (either implementation or a decision that it will not be implemented).  This is a useful feature for PKNCA to have, so it remains open.  But, it is not a feature that I have a common need for, so I have not implemented it.

The complexity of implementing it is handling scenarios when you do or don't have dosing information; the different routes of administration and ensuring that the results are accurate for each of them (intravascular bolus, extravascular bolus, and intravascular infusion).  It also requires ensuring that the results are accurate for single-dose vs. non-steady-state multiple-dose vs. steady-state multiple dose.  And, I believe that it needs the ability to do a different interpolation from the before vs the after side of the dosing time (e.g. IV bolus).  And in some cases, it should do that interpolation differently for different parameters (e.g. you may want interpolation of a point for AUC but not for Cmax). And, it needs a simple-for-the-user method of obtaining that information from the user.

And, it needs to record everything that is done so that someone reviewing the results can see where the differences between the initial and analysis dataset come from.

If my list above is too exhaustive, I'd be interested to see a proposal of how it could work more simply while still being effective.  (I have not put loads of thought into the feature as I don't often need it, so my list above may be more than is needed.)

I made an initial attempt that you can see in the `interp.extrap.conc.dose()` function, but that doesn't cover several scenarios.

The initial version of this does not require the ability to do all of the above, but it does need to be able to accurately detect when it should and should not work.  With those 

A pull request would be welcome if you'd like to take a shot.  I would suggest a detailed discussion of the features to be implemented and specifically how it would be implemented before jumping in since it is a complex topic.

**Comment by Sibojang9** [comment]
@billdenney I agree that it is too complex to implement and there would never to an end to the work. Instead of waiting for a consensus, I think that we can start with the simplest scenario for the most wanted features. e.g. point insertion required for time 0, conc 0 data.

**Comment by Sibojang9** [comment]
That is wonderful. Thanks you so much, Bill, - Sibo

**Comment by billdenney** [comment]
> That is wonderful. Thanks you so much, Bill, - Sibo

@Sibojang9, I'm glad that you like it.  Please let me know how well it works for you.
