### ISSUE TITLE
Linear-log trapezoidal method for AUC calculation

### ISSUE THREAD

**Issue by ksl31** [billdenney/pknca#23]
It would be nice to have linear-log trapezoidal method for AUC calculations in PKNCA.

**Comment by billdenney** [comment]
What is the difference between this and "lin up/log down" (which is currently supported)?

**Comment by ksl31** [comment]
Linear-log trapezoid uses the log trapezoidal rule after Cmax, or after C0 for IV bolus, if C0 > Cmax. Otherwise, the linear trapezoidal rule is used. If Cmax is not unique, then the first maximum is used. In  Linear up/log down, the linear trapezoidal rule is used when the concentration data is increasing, the logarithmic trapezoidal rule is used when the concentration data is decreasing. The two methods will have different AUC estimates when there's a multiple peak profile.

**Comment by billdenney** [comment]
Thanks for this description.  It will be pretty simple to add.

Do you know of any literature reference indicating the reason for choosing the first Cmax rather than the last (or the median)?

**Comment by DuyTran16** [comment]
I think choosing the first Cmax for competing equal Cmax in Linear-log trapezoidal method is just an arbitrary default,  just like the default selection of first tmax if more than one concentration is equal to Cmax in PKNCA or WinNonlin.  Maybe for Linear-log trapezoidal method feature in PKNCA in the future, you can have option selection of first (default), last, or the median as options for same Cmax for Linear-log trapezoidal method.

**Comment by billdenney** [comment]
@DuyTran16, that makes sense.  Do you think that it should always be the same as the selection for Tmax (if you select the first Tmax, last Tmax, or median Tmax-- do the same for linear-log trapezoidal rule), or do you think it should be a separate option?

**Comment by DuyTran16** [comment]
To be consistent, I agree that it's a good idea to set whatever the user has for Tmax for the definition of Tmax in linear-log trapezoidal rule.  The competing equal Cmax is a rare instance (the max concentrations must be absolutely identical in order to fall into this situation), and I could not find any literature reference other than it's an arbitrary default in WNL since Tmax for competing equal Cmax is set as the first Tmax.

**Comment by billdenney** [comment]
Thanks for the feedback.

The times I've seen equal Cmax in the past is when values were rounded.

**Comment by billdenney** [comment]
@ksl31 or @DuyTran16, I was looking to implement this, but I realized I'm unclear on how linear-log would work in some scenarios.  Can you please either point to a reference or help understand the behavior in data like this:

| time | conc | method to the next time |
| ---- | ---- | ---- |
| 0 | 0 | before Tmax, linear |
| 1 | 1 | before Tmax, linear |
| 2 | 4 | before Tmax, linear |
| 3 | 3 | before Tmax, linear |
| 4 | 4 | at Tmax, log |
| 5 | 1 | concentration is increasing, but the time is after Tmax, what happens?  By the above definition, I think: log |
| 6 | 2 | after Tmax, log |
| 7 | 1 | Not applicable, no next interval |

Can you please confirm what method would be used in each interval?  I'm assuming that the last Tmax (time = 4) is used here.  And, ideally, can you provide a literature reference for the reason to use linear-log instead of linear-up/log-down?

**Comment by DuyTran16** [comment]
Thanks for opening this discussion up.  The example you provided showed competing Cmax at times 2 and 4.  I could not find any reference other than WNL arbitrary specifying first tmax (time = 2 in your example) for the log trapezoidal after this first Cmax.

**If first Tmax is used:**
time | conc | method to the next time
-- | -- | --
0 | 0 | before Tmax1, linear
1 | 1 | before Tmax1, linear
2 | 4 | at Tmax1, log
3 | 3 | after Tmax1, log
4 | 4 | at Tmax2, log
5 | 1 | after Tmax2. log
6 | 2 | after Tmax2, log
7 | 1 | Not applicable, no next interval

**If last Tmax is used:**
time | conc | method to the next time
-- | -- | --
0 | 0 | before Tmax1, linear
1 | 1 | before Tmax1, linear
2 | 4 | at Tmax1, linear
3 | 3 | after Tmax1, linear
4 | 4 | at Tmax2, log
5 | 1 | after Tmax2. log
6 | 2 | after Tmax2, log
7 | 1 | Not applicable, no next interval

I terms of which to method  linear-log versus linear-up/log-down to use, my experience have been some folks just pick one by default specified in company's SOP to make sure things are done consistent.

**Comment by billdenney** [comment]
Thanks for the quick reply.  One other question:  How does it handle zeros in the middle?  I assume that it would use linear-- because it has to, but can you confirm:

time | conc | method to the next time
-- | -- | --
0 | 0 | before Tmax1, linear
1 | 1 | before Tmax1, linear
2 | 4 | at Tmax1, linear
3 | 3 | after Tmax1, linear
4 | 4 | at Tmax2 but zero, linear
5 | 0 | after Tmax2, but zero, linear
6 | 2 | after Tmax2, log
7 | 1 | Not applicable, no next interval

**Comment by DuyTran16** [comment]
Absolutely!  The use linear trapezoidal is appropriate in this case for handle of zero concentration in middle. 

This was how openNCA package https://github.com/tensfeldt/openNCA handled Linear-Log Trapezoidal AUC: 
https://github.com/tensfeldt/openNCA/blob/master/openNCA/R/auc_lin_log.R

**Comment by billdenney** [comment]
@DuyTran16 , Thanks, I'm working on implementing this now.  If other questions come up, I'll let you know.

**Comment by billdenney** [comment]
I've implemented "lin-log" integration.  Can you please give it a try and let me know if you find any issues?

I've created a vignette here that illustrates all available integration methods: http://billdenney.github.io/pknca/articles/v23-auc-integration-methods.html (There are a few visualization issues in the vignette described here #251, but they shouldn't affect actual interpretation.)
