### ISSUE TITLE
 lambda z and AUCinf

### ISSUE THREAD

**Issue by sibojan** [billdenney/pknca#37]
Hi Bill,
I have a question regarding the lambda z and AUC_inf. 
Would you please share how the current version of PKNCA package calculate the lambda z and AUC (tlast-inf)? If I set the ending time to inf,  the package will calculate the AUC (tlast to inf) based on the last sampling point and the lambda z?   Then the AUC (0-tlast) and AUC (tlast-inf) are summed up to get the AUC_inf?    Instead, if  I set the ending time to 24 hours for a 36 hours dataset, the AUCinf will be calculated as the sum of the AUC (0-24) and AUC (24-inf)?

Thank you,

Sibo

**Comment by billdenney** [comment]
That's a good question about how PKNCA looks at the data, and it's important to understand how PKNCA uses the data to ensure that you get the answer you're looking for from the package.

PKNCA thinks of data in two ways:  groups and intervals.  A `group` (as provided to PKNCAconc and PKNCAdose) is how it will subset the data to look at a single individual with a single treatment and a single analyte.  An `interval` is a subset of the group by time.  PKNCA will never look at data outside of the interval for whatever calculation you're requesting, and you have full control over PKNCA.  PKNCA will first subset the data by group then subset it by interval before doing any calculations.

So, to answer your question directly:
When set your interval to 0 to 24 and then request aucinf (lower case indicating how you request it from PKNCA), you've told PKNCA to only look at the time 0 to 24 hours for the calculation of AUCinf.  PKNCA first subsets your data to 0 to 24 hours then does the AUCinf calculation.  So, the specific way it will be calculated is calculate AUClast 0-24 then calculate half-life using the 0-24 hr data, and then extrapolate from Tlast to infinity using the half-life calculated up to 24 hours.

In many cases, you want to have AUCinf calculated using time with an upper bound of infinity because you want to include all points in a `group` with the AUClast and half-life calculations that support AUCinf.

Please let me know if that's clear and if you have any other questions.

**Comment by sibojan** [comment]
Hi Bill,

It is now very clear and confirmed my speculation as well. The documented
algorithm  does give extra confidence and peace for the package users.

Sibo
