### ISSUE TITLE
Dose-normalized values and more lambda z specification possibilities...

### ISSUE THREAD

**Issue by Brie-9582** [billdenney/pknca#41]
Hi Bill,

As discussed in a previous e-mail, it would be great if there could be the possibility for dose-normalized parameters (calculating them individually isn't an issue, but it would be nice to have them then also included in the summary table). As well, being able to have additional flexibility on the restrictions for the number of lambda z points (e.g. for comparing with other analyses, etc., that may have a specific number of lambda z points), would be great. I'm guessing this could be handled with something like a max.hl.points? or something where one can just straight out specify the number of desired points?

Thanks so much for this package and for incorporating all our requests :) !

**Comment by billdenney** [comment]
Thanks for helping me keep track by adding the feature requests here.  I just separated the two requests so that I don't miss one by completing the other.  This will be for the dose-normalized parameters.

The list of parameters that occur to me for dose normalization are the following.  Are there others that you'd add?

* auclast
* aucall
* aucinf.obs
* aucinf.pred
* aumclast
* aumcall
* cmax
* cmin
* clast.obs
* clast.pred
* cav
* ctrough

**Comment by Brie-9582** [comment]
Hi Bill,

Those are the ones that I would be able to think of for now. I think the
AUCs, Cmax, and Ctrough are the most important, at least to me, as they are
the values that tend to be compared more to each other in my experience.

Thanks again!

Sabrina



<https://www.facebook.com/Sabrina-Wiebe-Photography-116144586170/>Sabrina
Wiebe Photography
<https://www.facebook.com/Sabrina-Wiebe-Photography-116144586170/>

**Comment by billdenney** [comment]
Hi Sabrina,

I just added dose normalized parameters for each of the parameters in the list above with https://github.com/billdenney/pknca/commit/c39c2c6d4da40b074f33ce3e0a0757dbcc8b5291 .  The new parameter names have ".dn" appended to the parameter name.  For example, `cmax` becomes `cmax.dn`. 
 Can you please confirm that it works the way you'd expect?

Thanks,

Bill
