### ISSUE TITLE
Feature Request: max.hl.points

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca#42]
From #41: As well, being able to have additional flexibility on the restrictions for the number of lambda z points (e.g. for comparing with other analyses, etc., that may have a specific number of lambda z points), would be great. I'm guessing this could be handled with something like a max.hl.points? or something where one can just straight out specify the number of desired points?

**Comment by billdenney** [comment]
@Brie-9582, the most recent commit enables `exclude_half.life` as an argument to the `PKNCAconc` function.  The argument isn't precisely max.hl.points, but it can be used to the same effect.  To achieve max.hl.points-like effect, you can pre-treat your data with something like:

```
library(dplyr)
my_conc_data <- as.data.frame(Theoph)
max_hl_points <- 5
my_conc_data <- mutate(my_conc_data,
                       exclude_hl=rev(1:n()) > max_hl_points)
my_conc <- PKNCAconc(my_conc_data, conc~Time|Subject, exclude_half.life="exclude_hl")
```

**Comment by Brie-9582** [comment]
Thanks! Am I right that the purpose of the exclude_half.life is mainly to
be able to exclude particular points from half.life calculations or is the
purpose just to be able to do any of the calculations that don't require
half.life, while excluding the half.life and half.life related calculations
from overall presentation (e.g. because there isn't a long enough terminal
phase to accurately determine the half.life)? Either way, it is certainly a
nice feature :)

Thanks again!

Sabrina



<https://www.facebook.com/Sabrina-Wiebe-Photography-116144586170/>Sabrina
Wiebe Photography
<https://www.facebook.com/Sabrina-Wiebe-Photography-116144586170/>

**Comment by billdenney** [comment]
The point of exclude_half.life is to exclude points specifically from the half-life calculation.

The half-life will only be calculated if it is specifically requested or required for another parameter (like aucinf.pred or aucinf.obs).  And, if there are insufficient points for half-life determination, the half-life and dependent parameters will be set to NA in the output.
