### ISSUE TITLE
pknca summary cleanup (e.g. removal of rows with NA AUCs)

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#66]
My original question was: "how do I go about handling different intervals for the same data where some subsets have, say, farther out time points? If I do start=c(1,1) and end=(24,144) (for instance) my results look ugly. I'd like to specify the appropriate interval for the appropriate groups and be able to see all the data together."

To which @billdenney replied: "You are specifying the intervals the right way.  Please file as a feature request the simplification of the summary (which I think is what you’re asking—if not, please re-ask the question on github with an example to show what you’re seeing and what you’d like to see)."

Indeed, I think what I'm looking for is a summary that doesn't report the irrelevant rows.

**Comment by billdenney** [comment]
Thank you for putting this and the other issues up here to help others who may find themselves with the same in the future.

For this issue, I’ve thought about it before, but it is not necessarily clear how to make remove the irrelevant rows for the summary.

As an example, if you have an AUC 0-24, AUC 0-last, and an AUC 0-inf from the same starting time, then I can see that those could potentially be combined.  But, the way that PKNCA currently calculates 0-24 and 0-last are the same, so they overlap in the same column.

Other times, I have wanted the Tmax between 0 and 24 or 0 to 8 due to unusual dosing scenarios.

How would you suggest defining “irrelevant” rows for compression together?  (This is an honest question because I have not come up with a general method that I think will always work.)

**Comment by billdenney** [comment]
As I don't see an automatic way forward for this, I'm closing the issue.  If someone can suggest an automated way to make this simpler and cleaner, I'll definitely consider re-opening, and fixing the issue.
