### ISSUE TITLE
Exclude r- squared or R-squared adjusted

### ISSUE THREAD

**Issue by quantny** [billdenney/pknca#75]
Bill,

Question about excluding results based on r-squared. Is there an option to excluded based on R-squared adjusted. 

Thanks,

Justus

**Comment by billdenney** [comment]
Hi Justus,

`exclude_nca_min.hl.r.squared` excludes based on the r^2.  Do you specifically mean the **adjusted** r^2?  If so, there is no code to do that out of the box, but you can copy `exclude_nca_min.hl.r.squared` and make minor modifications so that it will work for adjusted instead of regular r^2.

Thanks,

Bill

**Comment by quantny** [comment]
Bill

Thanks that works. 

Justus
