### ISSUE TITLE
Intervals not starting at 0

### ISSUE THREAD

**Issue by john-harrold** [billdenney/pknca#82]
If I have data from 0.083 to 168 and I specify those as my start and stop times I get the reported tax and last values of:

tmax 0.000000e+00    <NA>
tlast 1.679170e+02    <NA>

Which are really relative values (relative to time zero of 0.083). Using these start/stop times gives me values for AUC and what not. Now if I set the interval to start at 0 and stop at 168, I get the correct max and last values but the AUCs parameters deprived from those are all NA.

**Comment by billdenney** [comment]
This is an intentional feature for the time-related parameters, and there is another way to get the answer you're wanting for the AUC.

For `tmax`, PKNCA is designed to work with both single- and multiple-dose data.  `tmax` is relative to the start of the interval.  The selection to use the start of the interval is made because if the interval is day 7 to 8 (168 to 192 hours) and `tmax` occurs at 1 hour after the beginning of the interval, `tmax` should be reported as `1` not `169`.

For `auclast`, try the `aucint.last` which does interpolation and extrapolation for you (the entire `aucint` family of calculations does improved imputation):

``` r
library(PKNCA)
d <- data.frame(time=c(0.08, 1, 2, 3, 4),
                conc=c(1, 0.5, 0.4, 0.3, 0.2),
                subject=1)
myconc <- PKNCAconc(data=d, conc~time|subject)
mydata <- PKNCAdata(myconc, intervals=data.frame(start=0, end=5, cmax=TRUE, tmax=TRUE, aucint.last=TRUE, auclast=TRUE))
myres <- pk.nca(mydata)
#> No dose information provided, calculations requiring dose will return NA.
#> Warning in pk.calc.auxc(conc = conc, time = time, ..., options = options, :
#> Requesting an AUC range starting (0) before the first measurement (0.08) is
#> not allowed
as.data.frame(myres)
#>   start end subject    PPTESTCD  PPORRES exclude
#> 1     0   5       1     auclast       NA    <NA>
#> 2     0   5       1 aucint.last 1.746018    <NA>
#> 3     0   5       1        cmax 1.000000    <NA>
#> 4     0   5       1        tmax 0.080000    <NA>
```

Created on 2018-08-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by billdenney** [comment]
I've just pushed a change that adds a section indicating the parameters that are in the calculation of intervals vignette.

**Comment by fabern** [comment]
Hi Bill,

Well, thank YOU for putting together this library!
And thanks for your reply. 

Okay, that's what I thought. I just wanted to be sure it's really not in there yet.

Currently, I do not understand the structure of the package enough to provide a Pull Request. 
I might have a look, once I find time. Though that won't be until next year.

Anyway, thanks for your reply.
Fabian

**Comment by billdenney** [comment]
@fabern, I think that this is resolved now.

By the way, I'd like for PKNCA to be more developer-friendly, too.  I have created one vignette to help show people how to create a new parameter (https://billdenney.github.io/pknca/articles/v80-writing-parameter-functions.html), and if you have questions, please let me know.  I'd like to update the vignette documentation.
