### ISSUE TITLE
Obs vs. Pred for AUCinf

### ISSUE THREAD

**Issue by sibojan** [billdenney/pknca#88]
Hi Bill,

This is a not PKNAC specific question, but I would really appreciate your input. I am wondering if there is any preference to use either AUC_inf obs or AUC_inf pred.  I found that PKNCA package reports both values, but I tend to select one of them in my PK study report.  I understand that selection of either one would not make a big difference since these two values are very close most of the time.

Thank you,

Sibo Jiang
Univ of Florida

**Comment by sibojan** [comment]
I heard that AUC_inf_obs is mostly used.

**Comment by billdenney** [comment]
Hi Sibo,

As far as I'm aware, it's a matter of preference.  (If anyone is aware of research on the topic, please add a link to the reference!)

AUC_inf_obs is my preference because it provides a continuous curve for the AUC integration.  (Otherwise, there is a discontinuity at Tlast where you jump from Clast_obs on the left to Clast_pred on the right.) In my mind, selecting AUC_inf_pred means that you don't trust the last time point, and you would prefer a more compartmental interpretation.

Thanks,

Bill

**Comment by sibojan** [comment]
Hi Bill，

Thank you for your comments.  I tried to run the script of plotting AUCinf-pred in the example "AUC-Calculation-with-PKNCA.Rmd". Interestingly, I found that the observed conc. are different from the predicted ones for the last three time points. Could you please clarify that? I thought that only the last time point was predicted. 

![index](https://user-images.githubusercontent.com/11802171/47954146-32152800-df5d-11e8-9ac1-3e250b4b1f54.png)

![snap19](https://user-images.githubusercontent.com/11802171/47954073-26753180-df5c-11e8-8fe7-71fba11245a6.jpg)

**Comment by sibojan** [comment]
I see. Thank you so much for the follow up.
