### ISSUE TITLE
Can you export AIC.list()?

### ISSUE THREAD

**Issue by matthewabirk** [billdenney/pknca#90]
AIC.list() is not exported in your NAMESPACE file. Therefore, I cannot call it with `PKNCA::AIC()`. Can you please add it to your NAMESPACE? I'd like to use it in a package but CRAN wants all dependencies to be explicitely called each time a function is used (e.g. `PKNCA::AIC()`).

**Comment by billdenney** [comment]
@matthewabirk, as described in #71, `AIC.list()` is not part of the core functionality of `PKNCA`, so I'd prefer not to export it.  I'm hoping to move `AIC.list()` to a better home than PKNCA (where it would be exported), so that the other package would manage the interface.

What is the package that you're planning to use it in?  Does it fit with core functionality there?  And, does that package have a relatively small number of dependencies?  (I'm getting at:  Would it be a good move to put `AIC.list()` in your package and have `PKNCA` depend on yours?)

**Comment by billdenney** [comment]
I'd suggest using the `broom` package's `glance()` function and extracting the AIC column (you would still have to choose the best model, too).
